name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: lts/*

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

# cancel the jobs if another workflow is kicked off for the same branch
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
